### ISSUE TITLE
Test failures, 1.7.4 on Debian

### ISSUE THREAD

**Issue by amckinstry** [sourceryinstitute/OpenCoarrays#271]
Issues seen in #212 heven't gone away, unfortunately. When tests are enabled properly, the following are seen.

(1) allocate_as_barrier_proc breaking on oversubscribed scenarios. Already known as #243.
(2) Segfaults in co_reduce on mips64el.
```
: co_reduce ........................***Exception: SegFault  0.56 sec
[mipsel-sil-01:27733] *** Process received signal ***
[mipsel-sil-01:27733] Signal: Segmentation fault (11)
[mipsel-sil-01:27733] Signal code: Address not mapped (1)
[mipsel-sil-01:27733] Failing at address: 0xffe85bf040
[mipsel-sil-01:27733] *** End of error message ***
```
Log: https://buildd.debian.org/status/fetch.php?pkg=open-coarrays&arch=mips64el&ver=1.7.4-4&stamp=1480837993

on Alpha:
```
Test project /<<PKGBUILDDIR>>/obj-alpha-linux-gnu
      Start  1: initialize_mpi
      Start  2: register
      Start  3: register_rename_me
 1/24 Test  #1: initialize_mpi ...................   Passed    0.41 sec
 2/24 Test  #2: register .........................   Passed    0.44 sec
 3/24 Test  #3: register_rename_me ...............   Passed    0.44 sec
      Start  4: register_rename_me_too
      Start  5: allocate_as_barrier
      Start  6: allocate_as_barrier_proc
 4/24 Test  #4: register_rename_me_too ...........   Passed    0.52 sec
      Start  7: get_array
 5/24 Test  #5: allocate_as_barrier ..............   Passed    1.46 sec
 6/24 Test  #6: allocate_as_barrier_proc .........   Passed    1.47 sec
 7/24 Test  #7: get_array ........................   Passed    1.05 sec
      Start  8: send_array
      Start  9: get_with_offset_1d
      Start 10: whole_get_array
 8/24 Test #10: whole_get_array ..................   Passed    0.61 sec
 9/24 Test  #9: get_with_offset_1d ...............   Passed    0.61 sec
      Start 11: strided_get
      Start 12: co_sum
10/24 Test  #8: send_array .......................   Passed    0.93 sec
      Start 13: co_broadcast
11/24 Test #12: co_sum ...........................***Failed  Required regular expression not found.Regex=[Test passed.
]  0.52 sec
number of images doesn't evenly divide into number of points
ERROR STOP 
number of images doesn't evenly divide into number of points
ERROR STOP --------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
number of images doesn't evenly divide into number of points
ERROR STOP 
[imago:11095] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[imago:11095] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

12/24 Test #11: strided_get ......................   Passed    0.52 sec
13/24 Test #13: co_broadcast .....................***Failed  Required regular expression not found.Regex=[Test passed.
]  0.33 sec
 Incorrect co_broadcast(           0 ) on image           2
ERROR STOP 
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

      Start 14: co_min
      Start 15: co_max
      Start 16: syncall
14/24 Test #14: co_min ...........................   Passed    0.51 sec
      Start 17: syncimages
15/24 Test #15: co_max ...........................   Passed    0.61 sec
      Start 18: duplicate_syncimages
16/24 Test #17: syncimages .......................   Passed    0.32 sec
      Start 19: co_reduce
17/24 Test #18: duplicate_syncimages .............   Passed    0.36 sec
      Start 20: syncimages_status
18/24 Test #19: co_reduce ........................   Passed    0.34 sec
19/24 Test #16: syncall ..........................   Passed    1.52 sec
      Start 21: hello_multiverse
      Start 22: coarray_burgers_pde
20/24 Test #22: coarray_burgers_pde ..............   Passed    0.52 sec
      Start 23: co_heat
21/24 Test #21: hello_multiverse .................   Passed    0.53 sec
      Start 24: asynchronous_hello_world
22/24 Test #20: syncimages_status ................   Passed    1.38 sec
23/24 Test #24: asynchronous_hello_world .........   Passed    0.41 sec
24/24 Test #23: co_heat ..........................   Passed   11.03 sec
```
Hurd-i386 fails badly:
https://buildd.debian.org/status/fetch.php?pkg=open-coarrays&arch=hurd-i386&ver=1.7.4-4&stamp=1480868021

m68k didn't run tests ? 
https://buildd.debian.org/status/fetch.php?pkg=open-coarrays&arch=m68k&ver=1.7.4-4&stamp=1480836000

**Comment by zbeekman** [comment]
@amckinstry Man, all these exotic and exciting architectures! It may take me some time to dig through these... Should we proceed with the Debian guest access paper work? I can look through logs etc. for the time being.

**Comment by zbeekman** [comment]
I haven't had time to dig in to this yet, but here are some initial impressions:

> (1) allocate_as_barrier_proc breaking on oversubscribed scenarios. Already known as #243.

Yes, after looking at this some more, I'm quite confident that this is true.

> (2) Segfaults in co_reduce on mips64el.

Maybe related to #172 ?

> number of images doesn't evenly divide into number of points
> ERROR STOP

I'm fairly confident that this is a problem with how I handled OpenMPI tests... Let me dig in to this, I think that either with the fixed `--oversubscribe` flag we might be back in business with oversubscribed OMPI, or otherwise, I'll have to be more careful of which tests require certain properties on the number of images they run with..

> Incorrect co_broadcast(           0 ) on image           2

This may be related to #243 as well...

**Comment by zbeekman** [comment]
> Hurd-i386 fails badly:
> https://buildd.debian.org/status/fetch.php?pkg=open-coarrays&arch=hurd-i386&ver=1.7.4-4&stamp=1480868021

Do you know if any oversubscribed MPI program will work on that machine? CMake seems convinced that it has only a single core. I'm also not seeing any `--oversubscribe` flags being passed to the test executables... Perhaps that's the reason. I'm guessing that having a go at cleaning up the OpenMPI CMake test execution logic has a decent chance of resolving this.

> m68k didn't run tests ?
> https://buildd.debian.org/status/fetch.php?pkg=open-coarrays&arch=m68k&ver=1.7.4-4&stamp=1480836000

Yes it appears it did not. Is there a script somewhere that controls this process? It is also using MPICH instead of OMPI, but the build appeared to progress as one would expect it to...

A final note: FYI, in the next release you'll set FC=gfortran-6 (or whatever it is in Debian) and CC=gcc-6 rather than pointing them to the MPI wrappers. CMake's FindMPI will handle MPI and the various MPI compile/linker arguments. If mpirun and/or the wrappers are on the path, CMake should pick this out without a problem. It is possible that this more "normal" CMake/MPI workflow may resolve some issues...

**Comment by amckinstry** [comment]
Thanks. The m68k case is of academic interest only; low usage numbers, and I don't think there are any multicore m68k machines ... highly unlikely to hit real users.
I'm working on the hurd issue now. 
And it appears the others are "known bugs", then, except for Alpha. I'll get the 'paperwork' done today.

**Comment by amckinstry** [comment]
Ok, the Hurd issue is likely to be due to an unrelated build issue in openmpi.

**Comment by zbeekman** [comment]
@amckinstry Ideally, I could get a vagrant or docker image/container up and running for the different archs... If you have any experience or thoughts on this, please let me know... not sure it's worth the hassle of all the debian paperwork. (Although I think things are pretty much done on my end, if I'm mistaken, please let me know.)

**Comment by amckinstry** [comment]
Apologies for the delay; i've been working on bugfixes for openmpi in Debian (moving to 2.02+git nov25) that I thought might be relevant to this (all my testing has been against openmpi).

I'm just going to rerun a test on the new openmpi and get back to you ASAP (though this week is Busy).

**Comment by zbeekman** [comment]
no worries... there are clearly some issues that I expect won't be resolved due to, e.g., [GCC PR 78505](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78505)

**Comment by zbeekman** [comment]
@amckinstry Just a quick update:

 - [X] Fix for #243 is on GFortran trunk and master here... we should be getting a new OpenCoarrays release out soon
 - [X] #293 was causing segfaults, potentially in a lot of places, but was doing so during `caf_finalize` which meant that, thanks to the way CTest works, we weren't noticing this since it happened after the test reported success....
 - [X] Another issue was fixed where a race condition could cause problems and the code would hang indefinitely if there were stopped images during a `sync images()` call.
 - [ ] co_reduce error may or may not be related to #172 (which appears to be a defect on the library side)
 - [ ] `co_broadcast` has me a bit perplexed... It may be a different symptom of the root cause of #172.
 - [ ] `co_sum` issue can be tracked at #267

**Comment by rouson** [comment]
Given the vintage, exotic nature of the one platform involved, and apparent redundancy with issue #243,  I recommend we close this issue.

**Comment by zbeekman** [comment]
hmmm let's keep it open, I was working on incorporating the patch they
apply before building... then I agree, let's re-asses with a more recent
release/build

**Comment by zbeekman** [comment]
@amckinstry Any chance you could give the latest release a test drive? If you can't get to it soonish, then we'll close this issue until we hear back.

FYI, if you happen to have MPICH 3.2 on any of the systems, there's a chance you may need to configure with `-DCAF_ENABLE_FAILED_IMAGES:BOOL=FALSE` to get the tests to pass due to a bug in MPICH 3.2

**Comment by amckinstry** [comment]
@zbeekman This works on Debian with openmpi; think you can close the issue. I'll give mpich 3.2 a test later, but i'm short of time right now.

The test 'navier-stokes' breaks for me as the code fails to link against the pre-built .a file - code needs to be rebuilt fPIC to work.

**Comment by zbeekman** [comment]
ah, ok. I'll look into this. As I said, with MPICH 3.2 you will need to disable failed images or apply the MPICH patch at: https://github.com/pmodels/mpich/pull/2730.patch. If you build with a slightly older MPICH the ULFM support won't be present and failed images will be turned off by default.
